
// This file has been generated by the GUI designer. Do not modify.

public partial class SettingsForm
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label labApi;

	private global::Gtk.Entry txtAPIKey;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label labProxy;

	private global::Gtk.Entry txtProxy;

	private global::Gtk.CheckButton chkDebugMode;

	private global::Gtk.HButtonBox hbuttonbox2;

	private global::Gtk.Button btnOK;

	private global::Gtk.Button btnCancel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget SettingsForm
		this.Name = "SettingsForm";
		this.Title = "Settings";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.BorderWidth = ((uint)(10));
		this.DefaultWidth = 480;
		// Container child SettingsForm.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labApi = new global::Gtk.Label ();
		this.labApi.Name = "labApi";
		this.labApi.LabelProp = "API key :";
		this.hbox2.Add (this.labApi);
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtAPIKey = new global::Gtk.Entry ();
		this.txtAPIKey.CanFocus = true;
		this.txtAPIKey.Name = "txtAPIKey";
		this.txtAPIKey.IsEditable = true;
		this.txtAPIKey.InvisibleChar = '●';
		this.hbox2.Add (this.txtAPIKey);
		this.vbox1.Add (this.hbox2);
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.labProxy = new global::Gtk.Label ();
		this.labProxy.Name = "labProxy";
		this.labProxy.LabelProp = "Proxy :";
		this.hbox1.Add (this.labProxy);
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtProxy = new global::Gtk.Entry ();
		this.txtProxy.CanFocus = true;
		this.txtProxy.Name = "txtProxy";
		this.txtProxy.IsEditable = true;
		this.txtProxy.InvisibleChar = '●';
		this.hbox1.Add (this.txtProxy);
		this.vbox1.Add (this.hbox1);
		// Container child vbox1.Gtk.Box+BoxChild
		this.chkDebugMode = new global::Gtk.CheckButton ();
		this.chkDebugMode.CanFocus = true;
		this.chkDebugMode.Name = "chkDebugMode";
		this.chkDebugMode.Label = "Debugging WakaTime?";
		this.chkDebugMode.DrawIndicator = true;
		this.chkDebugMode.UseUnderline = true;
		this.vbox1.Add (this.chkDebugMode);
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.hbuttonbox2.Spacing = 20;
		this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.btnOK = new global::Gtk.Button ();
		this.btnOK.CanFocus = true;
		this.btnOK.Name = "btnOK";
		this.btnOK.UseUnderline = true;
		this.btnOK.Label = "Save";
		this.hbuttonbox2.Add (this.btnOK);
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = "Cancel";
		this.hbuttonbox2.Add (this.btnCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnCancel]));
		this.vbox1.Add (this.hbuttonbox2);
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 149;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnOK.Clicked += new global::System.EventHandler (this.btnOK_Clicked);
		this.btnCancel.Clicked += new global::System.EventHandler (this.btnCancel_Clicked);
	}
}
